#!/usr/bin/with-contenv sh

# Install HomeSeer if container is started for the first time
if [ -e /DO_INSTALL ]

then
    echo "HomeSeer (re)install/update required at container first run. Installing at /HomeSeer..."
    curl "https://homeseer.com/updates4/linux_$HOMESEER_VERSION.tar.gz" | tar -xvz -C /
    rm -f /DO_INSTALL
else
    echo "HomeSeer already installed, not (re)installing/updating..."
fi
